"""Fail-closed policy for the Codex 0.156.1 app-server client protocol."""

from __future__ import annotations


CODEX_PROTOCOL_VERSION = "codex-cli 0.156.1"

# These methods were reviewed from ClientRequest.json generated by the pinned
# upstream. Read-only calls cannot change host, filesystem, account or thread
# state. Every other schema method is either handled as a managed lifecycle or
# mutation below, or deliberately rejected.
READ_ONLY_METHODS = {
    "account/rateLimits/read", "account/read", "account/usage/read",
    "account/workspaceMessages/read", "app/installed", "app/list", "app/read",
    "config/read", "configRequirements/read", "experimentalFeature/list",
    "externalAgentConfig/detect", "externalAgentConfig/import/readHistories",
    "fs/getMetadata", "fs/readDirectory", "fs/readFile", "hooks/list",
    "mcpServer/resource/read", "mcpServerStatus/list", "model/list",
    "modelProvider/capabilities/read", "permissionProfile/list", "plugin/installed",
    "plugin/list", "plugin/read", "plugin/share/list", "plugin/skill/read",
    "skills/list", "thread/attachment/list", "thread/goal/get", "thread/items/list",
    "thread/list", "thread/loaded/list", "thread/read", "thread/turns/list",
    "threadSection/list", "windowsSandbox/readiness",
}

LIFECYCLE_METHODS = {"initialize", "initialized", "thread/start", "thread/resume", "turn/start"}

# Mutations are permitted only for the connection holding the authoritative
# thread owner lock. Settings updates additionally use the authority transaction.
OWNER_MUTATION_METHODS = {
    "thread/approveGuardianDeniedAction", "thread/archive", "thread/attachment/add",
    "thread/attachment/remove", "thread/goal/clear", "thread/goal/set",
    "thread/inject_items", "thread/metadata/update", "thread/name/set",
    "thread/revert", "thread/rollback", "thread/section/move", "thread/shellCommand",
    "thread/unarchive", "thread/unsubscribe", "threadSection/create",
    "threadSection/delete", "threadSection/update", "turn/interrupt", "turn/steer",
    "thread/settings/update", "turn/settings/update",
}

REJECTED_INFERENCE_METHODS = {"review/start", "thread/compact/start", "thread/fork"}


def classify(method: object) -> str:
    if method in READ_ONLY_METHODS:
        return "read"
    if method in LIFECYCLE_METHODS:
        return "lifecycle"
    if method in OWNER_MUTATION_METHODS:
        return "owner_mutation"
    if method in REJECTED_INFERENCE_METHODS:
        return "rejected_inference"
    return "unknown"
